### ISSUE TITLE
ModuleNotFoundError: No module named 'scAnnot.utils' 

### ISSUE THREAD

**Issue by yojetsharma** [rnacentre/scAnnot#2]
(scarches) [yojetsharma@pakeeza ~]$ scAnnot /home/praghu/yojetsharma/scAnnot_test/multiome_snRNA_3npcs_reordered.h5ad ```
/home/praghu/yojetsharma/scAnnot_test/hbd_subset2_reordered.h5ad /home/praghu/yojetsharma/scvi_test/scvi_ref2/ --output /home/praghu/yojetsharma/scvi_test/test.h5ad
```
Traceback (most recent call last):
  File "/home/praghu/yojetsharma/.conda/envs/scarches/bin/scAnnot", line 33, in <module>
    sys.exit(load_entry_point('scAnnot==0.0.6', 'console_scripts', 'scAnnot')())
  File "/home/praghu/yojetsharma/.conda/envs/scarches/bin/scAnnot", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/praghu/yojetsharma/.conda/envs/scarches/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/home/praghu/yojetsharma/.conda/envs/scarches/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/praghu/yojetsharma/.local/lib/python3.9/site-packages/scAnnot/core.py", line 14, in <module>
    from .utils import get_max_depth
ModuleNotFoundError: No module named 'scAnnot.utils'
```

**Comment by changebio** [comment]
utils module has been removed. Try to use the new version 0.0.7
